function handleError(err){
  console.log(err);
  return;
}

module.exports = {
  handleError: handleError
}